copyright: "2025, By Prakhar Sharma"
logo: assets/kb_logo.png

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      navbar_align: content
      logo: 
        text: "Knowledge Base"
        image_dark: "assets/kb_logo.png"
      secondary_sidebar_items: page-toc, edit-this-page, sourcelink
      back_to_top_button: True
      use_edit_page_button: True
      external_links:
        - url: "https://github.com/praksharma"
          name: "GitHub Profile"
      header_links_before_dropdown: 6
      github_url: https://github.com/praksharma/Knowledge-Base
      footer_start: copyright
      footer_center: sphinx-version
    html_context:
      github_user: "praksharma"
      github_repo: "Knowledge-Base"
      github_version: "main"
      doc_path: "docs"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex